#pragma clang diagnostic ignored "-Weverything"
#pragma clang diagnostic warning "-Wall"
#pragma clang diagnostic ignored "-Wtypedef-redefinition"
#pragma clang diagnostic ignored "-Wunused-parameter"

#include "bih.c"
#include "box.c"
#include "prim.c"
#include "ray.c"
#include "render.c"
#include "sph.c"
#include "tex.c"
#include "tri.c"
#include "vec.c"
